# Generated by Django 4.2.4 on 2024-03-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_oredrdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrDetail',
            new_name='OrderDetail',
        ),
    ]
