# Generated by Django 4.2.4 on 2024-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_oredrdetail_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
