# Generated by Django 4.2.4 on 2024-03-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delivery_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_order',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='delivery_order',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_order',
            name='delivery_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery_order',
            name='payment_status',
            field=models.CharField(choices=[], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetail'),
        ),
    ]
