# Generated by Django 4.2.4 on 2024-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_delivery_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
    ]
