# Generated by Django 4.2.4 on 2024-03-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_delivery_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
